name: build-renode

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build (dotnet)
        run: |
          ./build.sh --net

      - name: Package
        run: |
          ./build.sh -p --net

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: renode-package
          path: output/packages/**
